#!/bin/sh
set -e

. /usr/local/bin/thread

magento_thread() {
  echo "sh /usr/local/bin/docker-ssmtp-entrypoint"
  sh /usr/local/bin/docker-ssmtp-entrypoint

	echo "sh /usr/local/bin/magento-entrypoint"
	sh /usr/local/bin/docker-magento-entrypoint

	# Execute all init scripts
	if [ -d /init.d ]  && [ "$(ls /init.d)" ]; then
			for f in /init.d/*.sh; do
					echo "sh $f"
					sh "$f"
			done
	fi
}

(run_thread magento_thread) 2>&1 &

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
		set -- php-fpm "$@"
fi

echo "Starting php-fpm..."
exec "$@"
