#!/bin/sh
set -e

if [ -z "${MAIL_ROOT}" ]; then
		export MAIL_ROOT=""
fi

if [ -z "${MAIL_HUB}" ]; then
		export MAIL_HUB=""
fi

if [ -z "${MAIL_AUTH_USER}" ]; then
		export MAIL_AUTH_USER=""
fi

if [ -z "${MAIL_AUTH_PASSWORD}" ]; then
		export MAIL_AUTH_PASSWORD=""
fi

if [ -z "${MAIL_AUTH_REWRITE_DOMAIN}" ]; then
		export MAIL_AUTH_REWRITE_DOMAIN=""
fi

if [ -z "${MAIL_AUTH_HOSTNAME}" ]; then
		export MAIL_AUTH_HOSTNAME=""
fi

envsubst '${MAIL_ROOT} ${MAIL_HUB} ${MAIL_AUTH_USER} ${MAIL_AUTH_PASSWORD} ${MAIL_AUTH_REWRITE_DOMAIN} ${MAIL_AUTH_HOSTNAME}' \
	< /etc/ssmtp/ssmtp.conf.template > /etc/ssmtp/ssmtp.conf