#!/bin/sh
set -e

. /usr/local/bin/thread

MAGENTO="${DOCUMENT_ROOT}"/bin/magento

_waiting_service() {
  HOST=$1
  PORT=$2

  until nc -z -v -w30 ${HOST} ${PORT}
  do
      echo "Waiting for ${HOST}:${PORT} connection..."
      # wait for 5 seconds before check again
      sleep 5
  done
}

_check_service() {
    # Redis
    if [ "${MAGENTO_CACHE_REDIS_HOST}" ]; then
        if [ -z "${MAGENTO_CACHE_REDIS_PORT}" ]; then
            MAGENTO_CACHE_REDIS_PORT=6379
        fi

        _waiting_service "${MAGENTO_CACHE_REDIS_HOST}" ${MAGENTO_CACHE_REDIS_PORT}
    fi

    # Database
    if [ "${MAGENTO_DATABASE_HOST}" ]; then
        if [ -z "${MAGENTO_DATABASE_PORT}" ]; then
            MAGENTO_DATABASE_PORT=3306
        fi

        _waiting_service "${MAGENTO_DATABASE_HOST}" ${MAGENTO_DATABASE_PORT}
    fi

    # Elasticsearch
    if [ "${MAGENTO_SEARCH_ENGINE_HOST}" ]; then
        if [ -z "${MAGENTO_SEARCH_ENGINE_PORT}" ]; then
            MAGENTO_SEARCH_ENGINE_PORT=9200
        fi

        _waiting_service "${MAGENTO_SEARCH_ENGINE_HOST}" ${MAGENTO_SEARCH_ENGINE_PORT}
    fi
}

_start_cron() {
    LOG_CRON=/home/magento/var/log

    echo "Create log directory ${LOG_CRON}."
    mkdir -p $LOG_CRON

    echo "Starting cron job..."
    crond -fbS -L ${LOG_CRON}/cron.log

    echo "Started cron job"
}

_main() {
    MAGENTO=${1}

    if [ -f "$MAGENTO" ]; then
        _check_service

        echo "${MAGENTO} setup:upgrade --keep-generated"
        "${MAGENTO}" setup:upgrade --keep-generated
    fi

    if [ "$MAGENTO_CRONTAB_ENABLED" ]; then
        _start_cron

        echo "${DOCUMENT_ROOT}/bin/magento cron:install 2>&1"
        "${DOCUMENT_ROOT}"/bin/magento cron:install 2>&1

        echo "${DOCUMENT_ROOT}/bin/magento cron:run 2>&1 &"
        "${DOCUMENT_ROOT}"/bin/magento cron:run 2>&1 &

        sed -i 's/no crontab for/#~ no crontab for/g' /etc/crontabs/magento
    fi
}

_main $MAGENTO

